CREATE ROLE admin_role;
CREATE ROLE manager_role;
CREATE ROLE sales_exec_role;
CREATE ROLE inventory_staff_role;
CREATE ROLE cashier_role;
CREATE ROLE support_staff_role;

GRANT SELECT ON users
TO manager_role, sales_exec_role, inventory_staff_role, cashier_role, support_staff_role;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin_role;

GRANT SELECT, INSERT, UPDATE, DELETE
ON products, orders, accomodates, customers
TO manager_role;

GRANT SELECT ON products, customers, orders TO sales_exec_role;
GRANT INSERT ON orders, customers TO sales_exec_role;
GRANT UPDATE ON orders TO sales_exec_role;

GRANT SELECT ON products, accomodates TO inventory_staff_role;
GRANT INSERT, UPDATE ON accomodates, stock_movements TO inventory_staff_role;

GRANT SELECT ON products, customers TO cashier_role;
GRANT INSERT ON orders, payments TO cashier_role;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO support_staff_role;

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE accomodates ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;


-- Create Roles
CREATE ROLE melaniejones LOGIN PASSWORD 'melaniejones';
CREATE ROLE hudsonmiguel LOGIN PASSWORD 'hudsonmiguel';
CREATE ROLE browndennis LOGIN PASSWORD 'browndennis';
CREATE ROLE christina28 LOGIN PASSWORD 'christina28';
CREATE ROLE mario85 LOGIN PASSWORD 'mario85';
CREATE ROLE mwallace LOGIN PASSWORD 'mwallace';
CREATE ROLE jennifer43 LOGIN PASSWORD 'jennifer43';
CREATE ROLE odavenport LOGIN PASSWORD 'odavenport';
CREATE ROLE amandabray LOGIN PASSWORD 'amandabray';
CREATE ROLE jenkinsjoe LOGIN PASSWORD 'jenkinsjoe';
CREATE ROLE oscarvasquez LOGIN PASSWORD 'oscarvasquez';
CREATE ROLE charles11 LOGIN PASSWORD 'charles11';
CREATE ROLE jacqueline87 LOGIN PASSWORD 'jacqueline87';
CREATE ROLE warrenshawn LOGIN PASSWORD 'warrenshawn';
CREATE ROLE gomezallen LOGIN PASSWORD 'gomezallen';
CREATE ROLE adyer LOGIN PASSWORD 'adyer';
CREATE ROLE chelsea62 LOGIN PASSWORD 'chelsea62';
CREATE ROLE stephenhall LOGIN PASSWORD 'stephenhall';
CREATE ROLE millershane LOGIN PASSWORD 'millershane';
CREATE ROLE kmcmahon LOGIN PASSWORD 'kmcmahon';
CREATE ROLE brucechristopher LOGIN PASSWORD 'brucechristopher';
CREATE ROLE welcheric LOGIN PASSWORD 'welcheric';
CREATE ROLE colleen32 LOGIN PASSWORD 'colleen32';
CREATE ROLE yhouston LOGIN PASSWORD 'yhouston';
CREATE ROLE christopher63 LOGIN PASSWORD 'christopher63';
CREATE ROLE yatespamela LOGIN PASSWORD 'yatespamela';
CREATE ROLE emily01 LOGIN PASSWORD 'emily01';
CREATE ROLE jeremyhull LOGIN PASSWORD 'jeremyhull';
CREATE ROLE dmorales LOGIN PASSWORD 'dmorales';
CREATE ROLE ynolan LOGIN PASSWORD 'ynolan';
CREATE ROLE peteradams LOGIN PASSWORD 'peteradams';
CREATE ROLE clayton93 LOGIN PASSWORD 'clayton93';
CREATE ROLE pespinoza LOGIN PASSWORD 'pespinoza';
CREATE ROLE jacqueline37 LOGIN PASSWORD 'jacqueline37';
CREATE ROLE roymary LOGIN PASSWORD 'roymary';
CREATE ROLE joel89 LOGIN PASSWORD 'joel89';
CREATE ROLE brownkaren LOGIN PASSWORD 'brownkaren';
CREATE ROLE qwoodard LOGIN PASSWORD 'qwoodard';
CREATE ROLE allenrandy LOGIN PASSWORD 'allenrandy';
CREATE ROLE danielgonzalez LOGIN PASSWORD 'danielgonzalez';
CREATE ROLE sflores LOGIN PASSWORD 'sflores';
CREATE ROLE veronica31 LOGIN PASSWORD 'veronica31';
CREATE ROLE anneflores LOGIN PASSWORD 'anneflores';
CREATE ROLE ariaspatricia LOGIN PASSWORD 'ariaspatricia';
CREATE ROLE emily79 LOGIN PASSWORD 'emily79';
CREATE ROLE nicolas91 LOGIN PASSWORD 'nicolas91';
CREATE ROLE vatkins LOGIN PASSWORD 'vatkins';
CREATE ROLE egarner LOGIN PASSWORD 'egarner';
CREATE ROLE matthewgreen LOGIN PASSWORD 'matthewgreen';
CREATE ROLE qfarley LOGIN PASSWORD 'qfarley';
CREATE ROLE psnyder LOGIN PASSWORD 'psnyder';
CREATE ROLE upacheco LOGIN PASSWORD 'upacheco';
CREATE ROLE chase01 LOGIN PASSWORD 'chase01';
CREATE ROLE leviluna LOGIN PASSWORD 'leviluna';
CREATE ROLE morenochristopher LOGIN PASSWORD 'morenochristopher';
CREATE ROLE pbraun LOGIN PASSWORD 'pbraun';
CREATE ROLE justinschneider LOGIN PASSWORD 'justinschneider';
CREATE ROLE zachary11 LOGIN PASSWORD 'zachary11';
CREATE ROLE wrightjonathan LOGIN PASSWORD 'wrightjonathan';
CREATE ROLE eklein LOGIN PASSWORD 'eklein';
CREATE ROLE brittany01 LOGIN PASSWORD 'brittany01';
CREATE ROLE diana87 LOGIN PASSWORD 'diana87';
CREATE ROLE chood LOGIN PASSWORD 'chood';
CREATE ROLE rodriguezdavid LOGIN PASSWORD 'rodriguezdavid';
CREATE ROLE cblankenship LOGIN PASSWORD 'cblankenship';
CREATE ROLE xnewman LOGIN PASSWORD 'xnewman';
CREATE ROLE llogan LOGIN PASSWORD 'llogan';
CREATE ROLE mark78 LOGIN PASSWORD 'mark78';
CREATE ROLE ashleywells LOGIN PASSWORD 'ashleywells';
CREATE ROLE cdiaz LOGIN PASSWORD 'cdiaz';
CREATE ROLE dkelly LOGIN PASSWORD 'dkelly';
CREATE ROLE mmcclure LOGIN PASSWORD 'mmcclure';
CREATE ROLE lpadilla LOGIN PASSWORD 'lpadilla';
CREATE ROLE jason66 LOGIN PASSWORD 'jason66';
CREATE ROLE marcus24 LOGIN PASSWORD 'marcus24';
CREATE ROLE xwilson LOGIN PASSWORD 'xwilson';
CREATE ROLE kaylatapia LOGIN PASSWORD 'kaylatapia';
CREATE ROLE brett43 LOGIN PASSWORD 'brett43';
CREATE ROLE james01 LOGIN PASSWORD 'james01';
CREATE ROLE jonesvirginia LOGIN PASSWORD 'jonesvirginia';
CREATE ROLE ambercunningham LOGIN PASSWORD 'ambercunningham';
CREATE ROLE rachel77 LOGIN PASSWORD 'rachel77';
CREATE ROLE perrybenjamin LOGIN PASSWORD 'perrybenjamin';
CREATE ROLE jake33 LOGIN PASSWORD 'jake33';
CREATE ROLE samanthabuckley LOGIN PASSWORD 'samanthabuckley';
CREATE ROLE marypayne LOGIN PASSWORD 'marypayne';
CREATE ROLE ricky04 LOGIN PASSWORD 'ricky04';
CREATE ROLE zperry LOGIN PASSWORD 'zperry';
CREATE ROLE misty55 LOGIN PASSWORD 'misty55';
CREATE ROLE gregory79 LOGIN PASSWORD 'gregory79';
CREATE ROLE villanuevasara LOGIN PASSWORD 'villanuevasara';
CREATE ROLE michellesmith LOGIN PASSWORD 'michellesmith';
CREATE ROLE james21 LOGIN PASSWORD 'james21';
CREATE ROLE devin36 LOGIN PASSWORD 'devin36';
CREATE ROLE cassandra49 LOGIN PASSWORD 'cassandra49';
CREATE ROLE gsnyder LOGIN PASSWORD 'gsnyder';
CREATE ROLE heather87 LOGIN PASSWORD 'heather87';
CREATE ROLE trannancy LOGIN PASSWORD 'trannancy';
CREATE ROLE wangashley LOGIN PASSWORD 'wangashley';
CREATE ROLE angela55 LOGIN PASSWORD 'angela55';
CREATE ROLE carpenterlisa LOGIN PASSWORD 'carpenterlisa';
CREATE ROLE jessicabrooks LOGIN PASSWORD 'jessicabrooks';
CREATE ROLE christopher50 LOGIN PASSWORD 'christopher50';
CREATE ROLE ashleyprice LOGIN PASSWORD 'ashleyprice';
CREATE ROLE amber55 LOGIN PASSWORD 'amber55';
CREATE ROLE ccontreras LOGIN PASSWORD 'ccontreras';
CREATE ROLE vanessacabrera LOGIN PASSWORD 'vanessacabrera';
CREATE ROLE peterprice LOGIN PASSWORD 'peterprice';
CREATE ROLE christopherjenkins LOGIN PASSWORD 'christopherjenkins';
CREATE ROLE bridget23 LOGIN PASSWORD 'bridget23';
CREATE ROLE jason85 LOGIN PASSWORD 'jason85';
CREATE ROLE matthewblankenship LOGIN PASSWORD 'matthewblankenship';
CREATE ROLE davidlaura LOGIN PASSWORD 'davidlaura';
CREATE ROLE robertross LOGIN PASSWORD 'robertross';
CREATE ROLE mcdonaldchristina LOGIN PASSWORD 'mcdonaldchristina';
CREATE ROLE ihoover LOGIN PASSWORD 'ihoover';
CREATE ROLE amandamartinez LOGIN PASSWORD 'amandamartinez';
CREATE ROLE donaldcruz LOGIN PASSWORD 'donaldcruz';
CREATE ROLE oosborne LOGIN PASSWORD 'oosborne';
CREATE ROLE xsmith LOGIN PASSWORD 'xsmith';
CREATE ROLE james26 LOGIN PASSWORD 'james26';
CREATE ROLE jacquelinesummers LOGIN PASSWORD 'jacquelinesummers';
CREATE ROLE michelleburch LOGIN PASSWORD 'michelleburch';
CREATE ROLE shannonvillanueva LOGIN PASSWORD 'shannonvillanueva';
CREATE ROLE danderson LOGIN PASSWORD 'danderson';
CREATE ROLE thomas95 LOGIN PASSWORD 'thomas95';
CREATE ROLE hawkinsdavid LOGIN PASSWORD 'hawkinsdavid';
CREATE ROLE smata LOGIN PASSWORD 'smata';
CREATE ROLE hrodriguez LOGIN PASSWORD 'hrodriguez';
CREATE ROLE brian02 LOGIN PASSWORD 'brian02';
CREATE ROLE timothytapia LOGIN PASSWORD 'timothytapia';
CREATE ROLE barnettaudrey LOGIN PASSWORD 'barnettaudrey';
CREATE ROLE diana57 LOGIN PASSWORD 'diana57';
CREATE ROLE robertsrichard LOGIN PASSWORD 'robertsrichard';
CREATE ROLE oreid LOGIN PASSWORD 'oreid';
CREATE ROLE elijahtate LOGIN PASSWORD 'elijahtate';
CREATE ROLE laura04 LOGIN PASSWORD 'laura04';
CREATE ROLE robertspatrick LOGIN PASSWORD 'robertspatrick';
CREATE ROLE kevinhenry LOGIN PASSWORD 'kevinhenry';
CREATE ROLE scottbrian LOGIN PASSWORD 'scottbrian';
CREATE ROLE gomezerika LOGIN PASSWORD 'gomezerika';
CREATE ROLE erinjones LOGIN PASSWORD 'erinjones';
CREATE ROLE rnunez LOGIN PASSWORD 'rnunez';
CREATE ROLE curtisburch LOGIN PASSWORD 'curtisburch';
CREATE ROLE andrew68 LOGIN PASSWORD 'andrew68';
CREATE ROLE erin13 LOGIN PASSWORD 'erin13';
CREATE ROLE sethcurtis LOGIN PASSWORD 'sethcurtis';
CREATE ROLE stephanie23 LOGIN PASSWORD 'stephanie23';
CREATE ROLE matthew11 LOGIN PASSWORD 'matthew11';
CREATE ROLE howardhill LOGIN PASSWORD 'howardhill';
CREATE ROLE melissalarson LOGIN PASSWORD 'melissalarson';
CREATE ROLE howardstephanie LOGIN PASSWORD 'howardstephanie';
CREATE ROLE david55 LOGIN PASSWORD 'david55';
CREATE ROLE calexander LOGIN PASSWORD 'calexander';
CREATE ROLE cristinazavala LOGIN PASSWORD 'cristinazavala';
CREATE ROLE randallwilliam LOGIN PASSWORD 'randallwilliam';
CREATE ROLE joseph73 LOGIN PASSWORD 'joseph73';
CREATE ROLE tuckerkatherine LOGIN PASSWORD 'tuckerkatherine';
CREATE ROLE wboyd LOGIN PASSWORD 'wboyd';
CREATE ROLE jsimpson LOGIN PASSWORD 'jsimpson';
CREATE ROLE floresdanny LOGIN PASSWORD 'floresdanny';
CREATE ROLE sturner LOGIN PASSWORD 'sturner';
CREATE ROLE bethany28 LOGIN PASSWORD 'bethany28';
CREATE ROLE barbarareed LOGIN PASSWORD 'barbarareed';
CREATE ROLE whitneylee LOGIN PASSWORD 'whitneylee';
CREATE ROLE istewart LOGIN PASSWORD 'istewart';
CREATE ROLE oguerra LOGIN PASSWORD 'oguerra';
CREATE ROLE cynthiakim LOGIN PASSWORD 'cynthiakim';
CREATE ROLE schwartztina LOGIN PASSWORD 'schwartztina';
CREATE ROLE droberts LOGIN PASSWORD 'droberts';
CREATE ROLE elizabeththompson LOGIN PASSWORD 'elizabeththompson';
CREATE ROLE rollinsbecky LOGIN PASSWORD 'rollinsbecky';
CREATE ROLE stricklandtricia LOGIN PASSWORD 'stricklandtricia';
CREATE ROLE angela00 LOGIN PASSWORD 'angela00';
CREATE ROLE tatetricia LOGIN PASSWORD 'tatetricia';
CREATE ROLE kathymiller LOGIN PASSWORD 'kathymiller';
CREATE ROLE qrussell LOGIN PASSWORD 'qrussell';
CREATE ROLE ortegatimothy LOGIN PASSWORD 'ortegatimothy';
CREATE ROLE joshuaaguilar LOGIN PASSWORD 'joshuaaguilar';
CREATE ROLE ljones LOGIN PASSWORD 'ljones';
CREATE ROLE jennifer36 LOGIN PASSWORD 'jennifer36';
CREATE ROLE arthurmcdonald LOGIN PASSWORD 'arthurmcdonald';
CREATE ROLE uwest LOGIN PASSWORD 'uwest';
CREATE ROLE dgreene LOGIN PASSWORD 'dgreene';
CREATE ROLE stephenross LOGIN PASSWORD 'stephenross';
CREATE ROLE gmann LOGIN PASSWORD 'gmann';
CREATE ROLE kayla27 LOGIN PASSWORD 'kayla27';
CREATE ROLE hahnlisa LOGIN PASSWORD 'hahnlisa';
CREATE ROLE olivia85 LOGIN PASSWORD 'olivia85';
CREATE ROLE clarkerin LOGIN PASSWORD 'clarkerin';
CREATE ROLE watsonchristopher LOGIN PASSWORD 'watsonchristopher';
CREATE ROLE ladams LOGIN PASSWORD 'ladams';
CREATE ROLE riverabruce LOGIN PASSWORD 'riverabruce';
CREATE ROLE hannah01 LOGIN PASSWORD 'hannah01';
CREATE ROLE rbrown LOGIN PASSWORD 'rbrown';
CREATE ROLE jessicahurley LOGIN PASSWORD 'jessicahurley';
CREATE ROLE qrobertson LOGIN PASSWORD 'qrobertson';
CREATE ROLE briankelly LOGIN PASSWORD 'briankelly';
CREATE ROLE kylebrown LOGIN PASSWORD 'kylebrown';
CREATE ROLE michaelmaldonado LOGIN PASSWORD 'michaelmaldonado';
CREATE ROLE sydneypotter LOGIN PASSWORD 'sydneypotter';
CREATE ROLE phuang LOGIN PASSWORD 'phuang';
CREATE ROLE michellefletcher LOGIN PASSWORD 'michellefletcher';
CREATE ROLE youngrobert LOGIN PASSWORD 'youngrobert';
CREATE ROLE pryan LOGIN PASSWORD 'pryan';
CREATE ROLE zwalker LOGIN PASSWORD 'zwalker';
CREATE ROLE annfrazier LOGIN PASSWORD 'annfrazier';
CREATE ROLE heidi45 LOGIN PASSWORD 'heidi45';
CREATE ROLE pjackson LOGIN PASSWORD 'pjackson';
CREATE ROLE ukennedy LOGIN PASSWORD 'ukennedy';
CREATE ROLE lewiselizabeth LOGIN PASSWORD 'lewiselizabeth';
CREATE ROLE junderwood LOGIN PASSWORD 'junderwood';
CREATE ROLE kathrynjoyce LOGIN PASSWORD 'kathrynjoyce';
CREATE ROLE aprilnewman LOGIN PASSWORD 'aprilnewman';
CREATE ROLE aprilmullins LOGIN PASSWORD 'aprilmullins';
CREATE ROLE ssullivan LOGIN PASSWORD 'ssullivan';
CREATE ROLE danielleclark LOGIN PASSWORD 'danielleclark';
CREATE ROLE anthony14 LOGIN PASSWORD 'anthony14';
CREATE ROLE travis71 LOGIN PASSWORD 'travis71';
CREATE ROLE johnphillips LOGIN PASSWORD 'johnphillips';
CREATE ROLE smithkayla LOGIN PASSWORD 'smithkayla';
CREATE ROLE rubengutierrez LOGIN PASSWORD 'rubengutierrez';
CREATE ROLE jennifer39 LOGIN PASSWORD 'jennifer39';
CREATE ROLE victorialopez LOGIN PASSWORD 'victorialopez';
CREATE ROLE samantha90 LOGIN PASSWORD 'samantha90';
CREATE ROLE heatherharris LOGIN PASSWORD 'heatherharris';
CREATE ROLE martinezcharles LOGIN PASSWORD 'martinezcharles';
CREATE ROLE lauren90 LOGIN PASSWORD 'lauren90';
CREATE ROLE brent62 LOGIN PASSWORD 'brent62';
CREATE ROLE rhodesamy LOGIN PASSWORD 'rhodesamy';
CREATE ROLE jlong LOGIN PASSWORD 'jlong';
CREATE ROLE erika63 LOGIN PASSWORD 'erika63';
CREATE ROLE tmalone LOGIN PASSWORD 'tmalone';
CREATE ROLE benjaminbishop LOGIN PASSWORD 'benjaminbishop';
CREATE ROLE tlynch LOGIN PASSWORD 'tlynch';
CREATE ROLE harringtonashley LOGIN PASSWORD 'harringtonashley';
CREATE ROLE warnerjamie LOGIN PASSWORD 'warnerjamie';
CREATE ROLE bscott LOGIN PASSWORD 'bscott';
CREATE ROLE morsepaul LOGIN PASSWORD 'morsepaul';
CREATE ROLE rebecca17 LOGIN PASSWORD 'rebecca17';
CREATE ROLE laura90 LOGIN PASSWORD 'laura90';

-- Grant Admin Role
GRANT admin_role TO melaniejones;

-- Grant Manager Role
GRANT manager_role TO hudsonmiguel;
GRANT manager_role TO browndennis;
GRANT manager_role TO christina28;
GRANT manager_role TO mario85;
GRANT manager_role TO mwallace;
GRANT manager_role TO jennifer43;
GRANT manager_role TO odavenport;
GRANT manager_role TO amandabray;
GRANT manager_role TO jenkinsjoe;
GRANT manager_role TO oscarvasquez;
GRANT manager_role TO charles11;
GRANT manager_role TO jacqueline87;

-- Grant Sales Executive Role
GRANT sales_exec_role TO warrenshawn;
GRANT sales_exec_role TO gomezallen;
GRANT sales_exec_role TO adyer;
GRANT sales_exec_role TO chelsea62;
GRANT sales_exec_role TO stephenhall;
GRANT sales_exec_role TO millershane;
GRANT sales_exec_role TO kmcmahon;
GRANT sales_exec_role TO brucechristopher;
GRANT sales_exec_role TO welcheric;
GRANT sales_exec_role TO colleen32;
GRANT sales_exec_role TO yhouston;
GRANT sales_exec_role TO christopher63;
GRANT sales_exec_role TO yatespamela;
GRANT sales_exec_role TO emily01;
GRANT sales_exec_role TO jeremyhull;
GRANT sales_exec_role TO dmorales;
GRANT sales_exec_role TO ynolan;
GRANT sales_exec_role TO peteradams;
GRANT sales_exec_role TO clayton93;
GRANT sales_exec_role TO pespinoza;
GRANT sales_exec_role TO jacqueline37;
GRANT sales_exec_role TO roymary;
GRANT sales_exec_role TO joel89;
GRANT sales_exec_role TO brownkaren;
GRANT sales_exec_role TO qwoodard;
GRANT sales_exec_role TO allenrandy;
GRANT sales_exec_role TO danielgonzalez;
GRANT sales_exec_role TO sflores;
GRANT sales_exec_role TO veronica31;
GRANT sales_exec_role TO anneflores;
GRANT sales_exec_role TO ariaspatricia;
GRANT sales_exec_role TO emily79;
GRANT sales_exec_role TO nicolas91;
GRANT sales_exec_role TO vatkins;
GRANT sales_exec_role TO egarner;
GRANT sales_exec_role TO matthewgreen;

-- Grant Inventory Staff Role
GRANT inventory_staff_role TO qfarley;
GRANT inventory_staff_role TO psnyder;
GRANT inventory_staff_role TO upacheco;
GRANT inventory_staff_role TO chase01;
GRANT inventory_staff_role TO leviluna;
GRANT inventory_staff_role TO morenochristopher;
GRANT inventory_staff_role TO pbraun;
GRANT inventory_staff_role TO justinschneider;
GRANT inventory_staff_role TO zachary11;
GRANT inventory_staff_role TO wrightjonathan;
GRANT inventory_staff_role TO eklein;
GRANT inventory_staff_role TO brittany01;
GRANT inventory_staff_role TO diana87;
GRANT inventory_staff_role TO chood;
GRANT inventory_staff_role TO rodriguezdavid;
GRANT inventory_staff_role TO cblankenship;
GRANT inventory_staff_role TO xnewman;
GRANT inventory_staff_role TO llogan;
GRANT inventory_staff_role TO mark78;
GRANT inventory_staff_role TO ashleywells;
GRANT inventory_staff_role TO cdiaz;
GRANT inventory_staff_role TO dkelly;
GRANT inventory_staff_role TO mmcclure;
GRANT inventory_staff_role TO lpadilla;
GRANT inventory_staff_role TO jason66;
GRANT inventory_staff_role TO marcus24;
GRANT inventory_staff_role TO xwilson;
GRANT inventory_staff_role TO kaylatapia;
GRANT inventory_staff_role TO brett43;
GRANT inventory_staff_role TO james01;
GRANT inventory_staff_role TO jonesvirginia;
GRANT inventory_staff_role TO ambercunningham;
GRANT inventory_staff_role TO rachel77;
GRANT inventory_staff_role TO perrybenjamin;
GRANT inventory_staff_role TO jake33;
GRANT inventory_staff_role TO samanthabuckley;
GRANT inventory_staff_role TO marypayne;
GRANT inventory_staff_role TO ricky04;
GRANT inventory_staff_role TO zperry;
GRANT inventory_staff_role TO misty55;
GRANT inventory_staff_role TO gregory79;
GRANT inventory_staff_role TO villanuevasara;
GRANT inventory_staff_role TO michellesmith;
GRANT inventory_staff_role TO james21;
GRANT inventory_staff_role TO devin36;
GRANT inventory_staff_role TO cassandra49;
GRANT inventory_staff_role TO gsnyder;
GRANT inventory_staff_role TO heather87;
GRANT inventory_staff_role TO trannancy;
GRANT inventory_staff_role TO wangashley;
GRANT inventory_staff_role TO angela55;
GRANT inventory_staff_role TO carpenterlisa;
GRANT inventory_staff_role TO jessicabrooks;
GRANT inventory_staff_role TO christopher50;
GRANT inventory_staff_role TO ashleyprice;
GRANT inventory_staff_role TO amber55;
GRANT inventory_staff_role TO ccontreras;
GRANT inventory_staff_role TO vanessacabrera;
GRANT inventory_staff_role TO peterprice;
GRANT inventory_staff_role TO christopherjenkins;
GRANT inventory_staff_role TO bridget23;
GRANT inventory_staff_role TO jason85;
GRANT inventory_staff_role TO matthewblankenship;
GRANT inventory_staff_role TO davidlaura;
GRANT inventory_staff_role TO robertross;
GRANT inventory_staff_role TO mcdonaldchristina;
GRANT inventory_staff_role TO ihoover;
GRANT inventory_staff_role TO amandamartinez;
GRANT inventory_staff_role TO donaldcruz;
GRANT inventory_staff_role TO oosborne;
GRANT inventory_staff_role TO xsmith;
GRANT inventory_staff_role TO james26;

-- Grant Cashier Role
GRANT cashier_role TO jacquelinesummers;
GRANT cashier_role TO michelleburch;
GRANT cashier_role TO shannonvillanueva;
GRANT cashier_role TO danderson;
GRANT cashier_role TO thomas95;
GRANT cashier_role TO hawkinsdavid;
GRANT cashier_role TO smata;
GRANT cashier_role TO hrodriguez;
GRANT cashier_role TO brian02;
GRANT cashier_role TO timothytapia;
GRANT cashier_role TO barnettaudrey;
GRANT cashier_role TO diana57;
GRANT cashier_role TO robertsrichard;
GRANT cashier_role TO oreid;
GRANT cashier_role TO elijahtate;
GRANT cashier_role TO laura04;
GRANT cashier_role TO robertspatrick;
GRANT cashier_role TO kevinhenry;
GRANT cashier_role TO scottbrian;
GRANT cashier_role TO gomezerika;
GRANT cashier_role TO erinjones;
GRANT cashier_role TO rnunez;
GRANT cashier_role TO curtisburch;
GRANT cashier_role TO andrew68;
GRANT cashier_role TO erin13;
GRANT cashier_role TO sethcurtis;
GRANT cashier_role TO stephanie23;
GRANT cashier_role TO matthew11;
GRANT cashier_role TO howardhill;
GRANT cashier_role TO melissalarson;
GRANT cashier_role TO howardstephanie;
GRANT cashier_role TO david55;
GRANT cashier_role TO calexander;
GRANT cashier_role TO cristinazavala;
GRANT cashier_role TO randallwilliam;
GRANT cashier_role TO joseph73;
GRANT cashier_role TO tuckerkatherine;
GRANT cashier_role TO wboyd;
GRANT cashier_role TO jsimpson;
GRANT cashier_role TO floresdanny;
GRANT cashier_role TO sturner;
GRANT cashier_role TO bethany28;
GRANT cashier_role TO barbarareed;
GRANT cashier_role TO whitneylee;
GRANT cashier_role TO istewart;
GRANT cashier_role TO oguerra;
GRANT cashier_role TO cynthiakim;
GRANT cashier_role TO schwartztina;

-- Grant Support Staff Role
GRANT support_staff_role TO droberts;
GRANT support_staff_role TO elizabeththompson;
GRANT support_staff_role TO rollinsbecky;
GRANT support_staff_role TO stricklandtricia;
GRANT support_staff_role TO angela00;
GRANT support_staff_role TO tatetricia;
GRANT support_staff_role TO kathymiller;
GRANT support_staff_role TO qrussell;
GRANT support_staff_role TO ortegatimothy;
GRANT support_staff_role TO joshuaaguilar;
GRANT support_staff_role TO ljones;
GRANT support_staff_role TO jennifer36;
GRANT support_staff_role TO arthurmcdonald;
GRANT support_staff_role TO uwest;
GRANT support_staff_role TO dgreene;
GRANT support_staff_role TO stephenross;
GRANT support_staff_role TO gmann;
GRANT support_staff_role TO kayla27;
GRANT support_staff_role TO hahnlisa;
GRANT support_staff_role TO olivia85;
GRANT support_staff_role TO clarkerin;
GRANT support_staff_role TO watsonchristopher;
GRANT support_staff_role TO ladams;
GRANT support_staff_role TO riverabruce;
GRANT support_staff_role TO hannah01;
GRANT support_staff_role TO rbrown;
GRANT support_staff_role TO jessicahurley;
GRANT support_staff_role TO qrobertson;
GRANT support_staff_role TO briankelly;
GRANT support_staff_role TO kylebrown;
GRANT support_staff_role TO michaelmaldonado;
GRANT support_staff_role TO sydneypotter;
GRANT support_staff_role TO phuang;
GRANT support_staff_role TO michellefletcher;
GRANT support_staff_role TO youngrobert;
GRANT support_staff_role TO pryan;
GRANT support_staff_role TO zwalker;
GRANT support_staff_role TO annfrazier;
GRANT support_staff_role TO heidi45;
GRANT support_staff_role TO pjackson;
GRANT support_staff_role TO ukennedy;
GRANT support_staff_role TO lewiselizabeth;
GRANT support_staff_role TO junderwood;
GRANT support_staff_role TO kathrynjoyce;
GRANT support_staff_role TO aprilnewman;
GRANT support_staff_role TO aprilmullins;
GRANT support_staff_role TO ssullivan;
GRANT support_staff_role TO danielleclark;
GRANT support_staff_role TO anthony14;
GRANT support_staff_role TO travis71;
GRANT support_staff_role TO johnphillips;
GRANT support_staff_role TO smithkayla;
GRANT support_staff_role TO rubengutierrez;
GRANT support_staff_role TO jennifer39;
GRANT support_staff_role TO victorialopez;
GRANT support_staff_role TO samantha90;
GRANT support_staff_role TO heatherharris;
GRANT support_staff_role TO martinezcharles;
GRANT support_staff_role TO lauren90;
GRANT support_staff_role TO brent62;
GRANT support_staff_role TO rhodesamy;
GRANT support_staff_role TO jlong;
GRANT support_staff_role TO erika63;
GRANT support_staff_role TO tmalone;
GRANT support_staff_role TO benjaminbishop;
GRANT support_staff_role TO tlynch;
GRANT support_staff_role TO harringtonashley;
GRANT support_staff_role TO warnerjamie;
GRANT support_staff_role TO bscott;
GRANT support_staff_role TO morsepaul;
GRANT support_staff_role TO rebecca17;
GRANT support_staff_role TO laura90;